//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Registrazione", ReplyAction="http://tempuri.org/IService1/RegistrazioneResponse")]
        ConsoleApp1.Classi.Utenti Registrazione(ConsoleApp1.Classi.Utenti utente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Registrazione", ReplyAction="http://tempuri.org/IService1/RegistrazioneResponse")]
        System.Threading.Tasks.Task<ConsoleApp1.Classi.Utenti> RegistrazioneAsync(ConsoleApp1.Classi.Utenti utente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoginUtente", ReplyAction="http://tempuri.org/IService1/LoginUtenteResponse")]
        ConsoleApp1.Classi.Utenti LoginUtente(ConsoleApp1.Classi.Utenti utente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoginUtente", ReplyAction="http://tempuri.org/IService1/LoginUtenteResponse")]
        System.Threading.Tasks.Task<ConsoleApp1.Classi.Utenti> LoginUtenteAsync(ConsoleApp1.Classi.Utenti utente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoginAdmin", ReplyAction="http://tempuri.org/IService1/LoginAdminResponse")]
        ConsoleApp1.Classi.Utenti LoginAdmin(ConsoleApp1.Classi.Utenti utenti);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoginAdmin", ReplyAction="http://tempuri.org/IService1/LoginAdminResponse")]
        System.Threading.Tasks.Task<ConsoleApp1.Classi.Utenti> LoginAdminAsync(ConsoleApp1.Classi.Utenti utenti);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FillListAttrezzi", ReplyAction="http://tempuri.org/IService1/FillListAttrezziResponse")]
        ConsoleApp1.Classi.Attrezzi[] FillListAttrezzi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FillListAttrezzi", ReplyAction="http://tempuri.org/IService1/FillListAttrezziResponse")]
        System.Threading.Tasks.Task<ConsoleApp1.Classi.Attrezzi[]> FillListAttrezziAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Addattrezzi", ReplyAction="http://tempuri.org/IService1/AddattrezziResponse")]
        System.ValueTuple<int, string> Addattrezzi(ConsoleApp1.Classi.Attrezzi attrezzi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Addattrezzi", ReplyAction="http://tempuri.org/IService1/AddattrezziResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<int, string>> AddattrezziAsync(ConsoleApp1.Classi.Attrezzi attrezzi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/viewSpecificheattrezzi", ReplyAction="http://tempuri.org/IService1/viewSpecificheattrezziResponse")]
        ConsoleApp1.Classi.Attrezzi viewSpecificheattrezzi(int id_attrezzo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/viewSpecificheattrezzi", ReplyAction="http://tempuri.org/IService1/viewSpecificheattrezziResponse")]
        System.Threading.Tasks.Task<ConsoleApp1.Classi.Attrezzi> viewSpecificheattrezziAsync(int id_attrezzo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/crearecarrello", ReplyAction="http://tempuri.org/IService1/crearecarrelloResponse")]
        System.ValueTuple<bool, string> crearecarrello(int id_attrezzo, int id_utente, int quntita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/crearecarrello", ReplyAction="http://tempuri.org/IService1/crearecarrelloResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<bool, string>> crearecarrelloAsync(int id_attrezzo, int id_utente, int quntita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Removeattrezzi", ReplyAction="http://tempuri.org/IService1/RemoveattrezziResponse")]
        System.ValueTuple<bool, string> Removeattrezzi(int id_attrezzo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Removeattrezzi", ReplyAction="http://tempuri.org/IService1/RemoveattrezziResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<bool, string>> RemoveattrezziAsync(int id_attrezzo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ViewCarrello", ReplyAction="http://tempuri.org/IService1/ViewCarrelloResponse")]
        System.ValueTuple<ConsoleApp1.Classi.Carrello[], string> ViewCarrello(int id_utente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ViewCarrello", ReplyAction="http://tempuri.org/IService1/ViewCarrelloResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<ConsoleApp1.Classi.Carrello[], string>> ViewCarrelloAsync(int id_utente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Removecarrello", ReplyAction="http://tempuri.org/IService1/RemovecarrelloResponse")]
        System.ValueTuple<bool, string> Removecarrello(int id_carrello);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Removecarrello", ReplyAction="http://tempuri.org/IService1/RemovecarrelloResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<bool, string>> RemovecarrelloAsync(int id_carrello);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ViewUtenti", ReplyAction="http://tempuri.org/IService1/ViewUtentiResponse")]
        System.ValueTuple<ConsoleApp1.Classi.Utenti[], string> ViewUtenti(int id_utente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ViewUtenti", ReplyAction="http://tempuri.org/IService1/ViewUtentiResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<ConsoleApp1.Classi.Utenti[], string>> ViewUtentiAsync(int id_utente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ViewVendite", ReplyAction="http://tempuri.org/IService1/ViewVenditeResponse")]
        System.ValueTuple<ConsoleApp1.Classi.Vendite[], string> ViewVendite(int id_utente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ViewVendite", ReplyAction="http://tempuri.org/IService1/ViewVenditeResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<ConsoleApp1.Classi.Vendite[], string>> ViewVenditeAsync(int id_utente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Buy", ReplyAction="http://tempuri.org/IService1/BuyResponse")]
        System.ValueTuple<bool, string> Buy(int id_utente, string indirizzoresidenza, string codicepromo, string cartacredoto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Buy", ReplyAction="http://tempuri.org/IService1/BuyResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<bool, string>> BuyAsync(int id_utente, string indirizzoresidenza, string codicepromo, string cartacredoto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebApplication1.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebApplication1.ServiceReference1.IService1>, WebApplication1.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsoleApp1.Classi.Utenti Registrazione(ConsoleApp1.Classi.Utenti utente) {
            return base.Channel.Registrazione(utente);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.Classi.Utenti> RegistrazioneAsync(ConsoleApp1.Classi.Utenti utente) {
            return base.Channel.RegistrazioneAsync(utente);
        }
        
        public ConsoleApp1.Classi.Utenti LoginUtente(ConsoleApp1.Classi.Utenti utente) {
            return base.Channel.LoginUtente(utente);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.Classi.Utenti> LoginUtenteAsync(ConsoleApp1.Classi.Utenti utente) {
            return base.Channel.LoginUtenteAsync(utente);
        }
        
        public ConsoleApp1.Classi.Utenti LoginAdmin(ConsoleApp1.Classi.Utenti utenti) {
            return base.Channel.LoginAdmin(utenti);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.Classi.Utenti> LoginAdminAsync(ConsoleApp1.Classi.Utenti utenti) {
            return base.Channel.LoginAdminAsync(utenti);
        }
        
        public ConsoleApp1.Classi.Attrezzi[] FillListAttrezzi() {
            return base.Channel.FillListAttrezzi();
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.Classi.Attrezzi[]> FillListAttrezziAsync() {
            return base.Channel.FillListAttrezziAsync();
        }
        
        public System.ValueTuple<int, string> Addattrezzi(ConsoleApp1.Classi.Attrezzi attrezzi) {
            return base.Channel.Addattrezzi(attrezzi);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<int, string>> AddattrezziAsync(ConsoleApp1.Classi.Attrezzi attrezzi) {
            return base.Channel.AddattrezziAsync(attrezzi);
        }
        
        public ConsoleApp1.Classi.Attrezzi viewSpecificheattrezzi(int id_attrezzo) {
            return base.Channel.viewSpecificheattrezzi(id_attrezzo);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.Classi.Attrezzi> viewSpecificheattrezziAsync(int id_attrezzo) {
            return base.Channel.viewSpecificheattrezziAsync(id_attrezzo);
        }
        
        public System.ValueTuple<bool, string> crearecarrello(int id_attrezzo, int id_utente, int quntita) {
            return base.Channel.crearecarrello(id_attrezzo, id_utente, quntita);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<bool, string>> crearecarrelloAsync(int id_attrezzo, int id_utente, int quntita) {
            return base.Channel.crearecarrelloAsync(id_attrezzo, id_utente, quntita);
        }
        
        public System.ValueTuple<bool, string> Removeattrezzi(int id_attrezzo) {
            return base.Channel.Removeattrezzi(id_attrezzo);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<bool, string>> RemoveattrezziAsync(int id_attrezzo) {
            return base.Channel.RemoveattrezziAsync(id_attrezzo);
        }
        
        public System.ValueTuple<ConsoleApp1.Classi.Carrello[], string> ViewCarrello(int id_utente) {
            return base.Channel.ViewCarrello(id_utente);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<ConsoleApp1.Classi.Carrello[], string>> ViewCarrelloAsync(int id_utente) {
            return base.Channel.ViewCarrelloAsync(id_utente);
        }
        
        public System.ValueTuple<bool, string> Removecarrello(int id_carrello) {
            return base.Channel.Removecarrello(id_carrello);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<bool, string>> RemovecarrelloAsync(int id_carrello) {
            return base.Channel.RemovecarrelloAsync(id_carrello);
        }
        
        public System.ValueTuple<ConsoleApp1.Classi.Utenti[], string> ViewUtenti(int id_utente) {
            return base.Channel.ViewUtenti(id_utente);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<ConsoleApp1.Classi.Utenti[], string>> ViewUtentiAsync(int id_utente) {
            return base.Channel.ViewUtentiAsync(id_utente);
        }
        
        public System.ValueTuple<ConsoleApp1.Classi.Vendite[], string> ViewVendite(int id_utente) {
            return base.Channel.ViewVendite(id_utente);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<ConsoleApp1.Classi.Vendite[], string>> ViewVenditeAsync(int id_utente) {
            return base.Channel.ViewVenditeAsync(id_utente);
        }
        
        public System.ValueTuple<bool, string> Buy(int id_utente, string indirizzoresidenza, string codicepromo, string cartacredoto) {
            return base.Channel.Buy(id_utente, indirizzoresidenza, codicepromo, cartacredoto);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<bool, string>> BuyAsync(int id_utente, string indirizzoresidenza, string codicepromo, string cartacredoto) {
            return base.Channel.BuyAsync(id_utente, indirizzoresidenza, codicepromo, cartacredoto);
        }
    }
}
