//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Registrazione", ReplyAction="http://tempuri.org/IService1/RegistrazioneResponse")]
        string Registrazione(string nome, string cognome, string codicefiscale, System.DateTime datanascita, string email, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Registrazione", ReplyAction="http://tempuri.org/IService1/RegistrazioneResponse")]
        System.Threading.Tasks.Task<string> RegistrazioneAsync(string nome, string cognome, string codicefiscale, System.DateTime datanascita, string email, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        string Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        System.Threading.Tasks.Task<string> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoginAdmin", ReplyAction="http://tempuri.org/IService1/LoginAdminResponse")]
        string LoginAdmin(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoginAdmin", ReplyAction="http://tempuri.org/IService1/LoginAdminResponse")]
        System.Threading.Tasks.Task<string> LoginAdminAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaAttrezzi", ReplyAction="http://tempuri.org/IService1/ListaAttrezziResponse")]
        System.Data.DataTable ListaAttrezzi(int id_attressi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaAttrezzi", ReplyAction="http://tempuri.org/IService1/ListaAttrezziResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListaAttrezziAsync(int id_attressi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Addattrezzi", ReplyAction="http://tempuri.org/IService1/AddattrezziResponse")]
        string Addattrezzi(int id_attrezzo, string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Addattrezzi", ReplyAction="http://tempuri.org/IService1/AddattrezziResponse")]
        System.Threading.Tasks.Task<string> AddattrezziAsync(int id_attrezzo, string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Removeattrezzi", ReplyAction="http://tempuri.org/IService1/RemoveattrezziResponse")]
        string Removeattrezzi(int id_attrezzo, string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Removeattrezzi", ReplyAction="http://tempuri.org/IService1/RemoveattrezziResponse")]
        System.Threading.Tasks.Task<string> RemoveattrezziAsync(int id_attrezzo, string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaCarrello", ReplyAction="http://tempuri.org/IService1/ListaCarrelloResponse")]
        System.Data.DataTable ListaCarrello(int id_carrello);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaCarrello", ReplyAction="http://tempuri.org/IService1/ListaCarrelloResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListaCarrelloAsync(int id_carrello);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCarrello", ReplyAction="http://tempuri.org/IService1/AddCarrelloResponse")]
        string AddCarrello(int id_carrello);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCarrello", ReplyAction="http://tempuri.org/IService1/AddCarrelloResponse")]
        System.Threading.Tasks.Task<string> AddCarrelloAsync(int id_carrello);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaUtenti", ReplyAction="http://tempuri.org/IService1/ListaUtentiResponse")]
        System.Data.DataTable ListaUtenti(int id_utente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaUtenti", ReplyAction="http://tempuri.org/IService1/ListaUtentiResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListaUtentiAsync(int id_utente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Addutente", ReplyAction="http://tempuri.org/IService1/AddutenteResponse")]
        string Addutente(int id_nome, string cognome, string codicefiscale);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Addutente", ReplyAction="http://tempuri.org/IService1/AddutenteResponse")]
        System.Threading.Tasks.Task<string> AddutenteAsync(int id_nome, string cognome, string codicefiscale);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Removeutente", ReplyAction="http://tempuri.org/IService1/RemoveutenteResponse")]
        string Removeutente(int id_nome, string cognome, string codicefiscale);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Removeutente", ReplyAction="http://tempuri.org/IService1/RemoveutenteResponse")]
        System.Threading.Tasks.Task<string> RemoveutenteAsync(int id_nome, string cognome, string codicefiscale);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaVendite", ReplyAction="http://tempuri.org/IService1/ListaVenditeResponse")]
        System.Data.DataTable ListaVendite(int id_vendita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListaVendite", ReplyAction="http://tempuri.org/IService1/ListaVenditeResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListaVenditeAsync(int id_vendita);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebApplication1.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebApplication1.ServiceReference1.IService1>, WebApplication1.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Registrazione(string nome, string cognome, string codicefiscale, System.DateTime datanascita, string email, string username, string password) {
            return base.Channel.Registrazione(nome, cognome, codicefiscale, datanascita, email, username, password);
        }
        
        public System.Threading.Tasks.Task<string> RegistrazioneAsync(string nome, string cognome, string codicefiscale, System.DateTime datanascita, string email, string username, string password) {
            return base.Channel.RegistrazioneAsync(nome, cognome, codicefiscale, datanascita, email, username, password);
        }
        
        public string Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<string> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public string LoginAdmin(string username, string password) {
            return base.Channel.LoginAdmin(username, password);
        }
        
        public System.Threading.Tasks.Task<string> LoginAdminAsync(string username, string password) {
            return base.Channel.LoginAdminAsync(username, password);
        }
        
        public System.Data.DataTable ListaAttrezzi(int id_attressi) {
            return base.Channel.ListaAttrezzi(id_attressi);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListaAttrezziAsync(int id_attressi) {
            return base.Channel.ListaAttrezziAsync(id_attressi);
        }
        
        public string Addattrezzi(int id_attrezzo, string nome) {
            return base.Channel.Addattrezzi(id_attrezzo, nome);
        }
        
        public System.Threading.Tasks.Task<string> AddattrezziAsync(int id_attrezzo, string nome) {
            return base.Channel.AddattrezziAsync(id_attrezzo, nome);
        }
        
        public string Removeattrezzi(int id_attrezzo, string nome) {
            return base.Channel.Removeattrezzi(id_attrezzo, nome);
        }
        
        public System.Threading.Tasks.Task<string> RemoveattrezziAsync(int id_attrezzo, string nome) {
            return base.Channel.RemoveattrezziAsync(id_attrezzo, nome);
        }
        
        public System.Data.DataTable ListaCarrello(int id_carrello) {
            return base.Channel.ListaCarrello(id_carrello);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListaCarrelloAsync(int id_carrello) {
            return base.Channel.ListaCarrelloAsync(id_carrello);
        }
        
        public string AddCarrello(int id_carrello) {
            return base.Channel.AddCarrello(id_carrello);
        }
        
        public System.Threading.Tasks.Task<string> AddCarrelloAsync(int id_carrello) {
            return base.Channel.AddCarrelloAsync(id_carrello);
        }
        
        public System.Data.DataTable ListaUtenti(int id_utente) {
            return base.Channel.ListaUtenti(id_utente);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListaUtentiAsync(int id_utente) {
            return base.Channel.ListaUtentiAsync(id_utente);
        }
        
        public string Addutente(int id_nome, string cognome, string codicefiscale) {
            return base.Channel.Addutente(id_nome, cognome, codicefiscale);
        }
        
        public System.Threading.Tasks.Task<string> AddutenteAsync(int id_nome, string cognome, string codicefiscale) {
            return base.Channel.AddutenteAsync(id_nome, cognome, codicefiscale);
        }
        
        public string Removeutente(int id_nome, string cognome, string codicefiscale) {
            return base.Channel.Removeutente(id_nome, cognome, codicefiscale);
        }
        
        public System.Threading.Tasks.Task<string> RemoveutenteAsync(int id_nome, string cognome, string codicefiscale) {
            return base.Channel.RemoveutenteAsync(id_nome, cognome, codicefiscale);
        }
        
        public System.Data.DataTable ListaVendite(int id_vendita) {
            return base.Channel.ListaVendite(id_vendita);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListaVenditeAsync(int id_vendita) {
            return base.Channel.ListaVenditeAsync(id_vendita);
        }
    }
}
